### PR TITLE
Add new svg phone and up arrow icons

### PR DESCRIPTION
**Pull request by lroliphant**
* for use in mobile version of new businesses lp
* version without circle
* bump patch version

### CODE REVIEW

**Comment by lroliphant** [comment]
@RazvanDH :)

**Comment by RazvanDH** [comment]
* name of the file must have the next available `uEXX` number (`uE20-phone.svg`)
* the SVG seems to be empty

**Comment by RazvanDH** [comment]
:sheep: :it: **LGTM**

**Comment by RazvanDH** [comment]
Still **LGTM** :sheep: :it:

**Pull request merged**
