### PR TITLE
CI: Use scss-lint for SCSS linting

### PR DESCRIPTION
**Pull request by sgerrand**
:information_desk_person: These changes add the [`scss-lint`](https://github.com/causes/scss-lint) gem and an initial configuration for CircleCI.

Note that the build will fail until some SCSS files are added to this repository. :smiley_cat:

### CODE REVIEW

**Comment by sgerrand** [comment]
> my changes got merged.

:heart_eyes_cat: Will update.

**Comment by sgerrand** [comment]
@igoratron: There's lots of errors being reported by scss-lint. Should I fix them?

**Comment by igoratron** [comment]
@sgerrand don't think so because @RazvanDH is working on a new version anyway. Just let him know sass-lint is now available

**Comment by sgerrand** [comment]
@igoratron: I've added a configuration file to disable the failing linters.

@RazvanDH: Once you've finished your work, you'll need to delete the 'linters' line and all those below in `.sccs-lint.yml`.

**Comment by RazvanDH** [comment]
@sgerrand - still work in progress, will have a stable structure soon. We'll deal with scss-linting then

**Comment by sgerrand** [comment]
> will have a stable structure soon

:raised_hands:

**Pull request merged**
