### PR TITLE
Add z-index to `form-default_tooltip`

### PR DESCRIPTION
**Pull request by guyfedwards**
Tooltip showing underneath other page content, specifically on lead gen
form

https://jira.fundingcircle.com/browse/GH-177

### CODE REVIEW

**Comment by thejuanitalee** [comment]
@guyfedwards Delete your `dist` files?

**Comment by guyfedwards** [comment]
@thejuanitalee @RazvanDH Would the `dist` files not need to be up to date? If the `dist` files are in the repo, they should be up to date?

**Comment by RazvanDH** [comment]
@guyfedwards please bump the version in `bower.json` and `package.json`. Also, we build the `dist` directory manually after merging to master.

Steps:
1) merge to master
2) rebuild master
3) tag master

**Comment by RazvanDH** [comment]
**LGTM**

**Pull request merged**
