### PR TITLE
Added updated license information

### PR DESCRIPTION
**Pull request by paddyo**
We are now using the MIT license as this repo is open source

### CODE REVIEW

**Comment by sgerrand** [comment]
Small nitpicks: can the content of the license file become plain text (remove the '# ' from the first line) and renamed to `LICENSE`.

As for adding the license itself, let's get confirmation out-of-band from all of the relevant parties.

**Comment by paddyo** [comment]
B-b-but all the cool repo's use markdown! (Will change). MIT review is in the pipeline, legal want a look over, so will mark as blocked until confirmed!

**Comment by igoratron** [comment]
@paddyo what's happening with this?

**Comment by paddyo** [comment]
This has been done in another PR

**Pull request closed without merging**
