### PR TITLE
Update to paddings on wrap utility class

### PR DESCRIPTION
**Pull request by lroliphant**
* keep default padding of 16px on mobile devices
* increase padding to 24px on screen widths larger than 640px
* small fix - 1st step towards wider design/dev review of column padding across site
* bump patch version

### CODE REVIEW

**Comment by lroliphant** [comment]
@thejuanitalee for review from US side please :eyes:

**Comment by thejuanitalee** [comment]
LGTM.

One question, do we push the dist changes as well? It's been awhile for me.

**Comment by igoratron** [comment]
@lroliphant can we merge this?

**Comment by lroliphant** [comment]
@igoratron just waiting for Adam to confirm he is happy and then yes

**Comment by RazvanDH** [comment]
**LGTM** :sheep: :it:

**Pull request merged**
