### PR TITLE
Add toggle switch

### PR DESCRIPTION
**Pull request by thejuanitalee**
* On and off feature

### CODE REVIEW

**Comment by RazvanDH** [comment]
@thejuanitalee - you need to update the `sass-common` version

**Comment by thejuanitalee** [comment]
@RazvanDH beep-boop-beep-beep-boop DONE.

**Comment by thejuanitalee** [comment]
p.s. not sure how the `dist` stuff snuck in my branch.

**Comment by RazvanDH** [comment]
@thejuanitalee - thanks for bumping the version. Can you please remove the `dist` directory?

**Comment by thejuanitalee** [comment]
@RazvanDH removed the dist dir

**Comment by RazvanDH** [comment]
@thejuanitalee - sorry, I wasn't clear with what I said: please remove the `dist` dir from your commit, not completely remove it :sob:

**Comment by thejuanitalee** [comment]
I was like... ok... I will... -_____-

**Pull request closed without merging**
